/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val hold = domain.Hold.fromConfigFile("properties.txt")
		
		    	val StepTime = 345 
		//      var num_empty_slot = 4        // caso simulato in cui la hold sia libera
		        var engaged = false			// stato cargoservice
		        var SlotTarget : domain.ISlot? = null  //nullable
		        var holdState = hold.toString()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | starts - Inizializzazione Orchestratore Cargo Service: $holdState")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 engaged = false  
						CommUtils.outgreen("$name | [DISENGAGED] attendo request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("loadRequest"))
					interrupthandle(edgeName="t01",targetState="handleAlarm",cond=whenEvent("sensorAlarm"),interruptedStateTransitions)
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  !hold.isFull() && engaged == false  
						 ){ 
							    		val freeSlot = hold.findFreeSlot()
							    		SlotTarget = freeSlot	//assegno a var globale
							    		val SlotTargetId = freeSlot?.getName() ?: "Unknown"
						answer("loadRequest", "loadEngaged", "loadEngaged($SlotTargetId)"   )  
						
						//	            num_empty_slot --
							            engaged = true
						forward("startBlink", "startBlink(0)" ,"led" ) 
						CommUtils.outmagenta("$name | [ENGAGED] Request di carico accettata, slot disponibile: $SlotTargetId")
						}
						else
						 {if(  engaged == true  
						  ){answer("loadRequest", "retryLater", "retryLater(0)"   )  
						 }
						 else
						  {answer("loadRequest", "loadRejected", "loadRejected(0)"   )  
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingContainer", cond=doswitchGuarded({ engaged == true  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( engaged == true  
					) }) )
				}	 
				state("waitingContainer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [ENGAGED] attengo container entro 30s")
						emit("startSensorRecording", "startSensortRecording(1)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitingContainer", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitingContainer", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t12",targetState="handleTimeoutExpired",cond=whenTimeout("local_tout_"+name+"_waitingContainer"))   
					transition(edgeName="t13",targetState="handleContainerDetected",cond=whenEvent("containerDetected"))
					interrupthandle(edgeName="t14",targetState="handleAlarm",cond=whenEvent("sensorAlarm"),interruptedStateTransitions)
				}	 
				state("handleTimeoutExpired") { //this:State
					action { //it:State
						CommUtils.outred("$name | [DISENGAGED] Timeout 30s scaduto, back to disengaged")
						
						            engaged = false
						//            num_empty_slot++
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						emit("timeOut", "timeOut(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleContainerDetected") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outgreen("$name | [ENGAGED] Container rilevato ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startMoveToSensorArea", cond=doswitch() )
				}	 
				state("startMoveToSensorArea") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [ENGAGED] Robot move container verso Sensor Area")
						
									var SensorAreaX = hold.getIoPort().getX()
									var SensorAreaY = hold.getIoPort().getY()
						request("moverobot", "moverobot($SensorAreaX,$SensorAreaY,$StepTime)" ,"robotsmart26" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="startMoveToSlot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t06",targetState="handleDepositFailed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t07",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("startMoveToSlot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [ENGAGED] Carico recupertato in sensor area! Robot muove container verso Slot5")
						
									var Slot5X = hold.getSlot5().getX()
									var Slot5Y = hold.getSlot5().getY()
						request("moverobot", "moverobot($Slot5X,$Slot5Y,$StepTime)" ,"robotsmart26" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="markingSlot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t09",targetState="handleDepositFailed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t010",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("markingSlot5") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [ENGAGED] container arrivato in slot5: inizio procedura di labeling ")
						delay(5000) 
						CommUtils.outgreen("$name | [ENGAGED] container etichettato, robot in movimento  verso  $SlotTarget")
						
									//Acquisizione coordinate target
									var CoordTarget = hold.getSlotCoord(SlotTarget)
									var TargetX = CoordTarget.getX()
									var TargetY = CoordTarget.getY()
						request("moverobot", "moverobot($TargetX,$TargetY,$StepTime)" ,"robotsmart26" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="handleDepositSuccess",cond=whenReply("moverobotdone"))
					transition(edgeName="t012",targetState="handleDepositFailed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t013",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("handleDepositSuccess") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [DISENGAGED] container depositato con successo nello slot $SlotTarget")
						
									//occupazione slot da parte del container engaged
									SlotTarget?.putContainer()
									var holdState = hold.toString()
									
									
									engaged = false
						CommUtils.outgreen("$name | Stato Hold: $holdState")
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						emit("loadEnded", "loadEnded(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleDepositFailed") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outred("$name | [DISENGAGED] deposito fallito, RobotSmart26 non ha completato il piano")
						
									engaged = false
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						emit("timeOut", "timeOut(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outred("$name | [OUT OF SERVICE] Allarme Out of Service rilevato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfService", cond=doswitch() )
				}	 
				state("outOfService") { //this:State
					action { //it:State
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						CommUtils.outred("$name | [OUT OF SERVICE] Sistema out of service!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="tEndOOS14",targetState="handleEndOOS",cond=whenEvent("endOOS"))
				}	 
				state("handleEndOOS") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [ENDING OOS] Riprendo da idle")
						if(  engaged == true  
						 ){
						                engaged = false
						//                num_empty_slot++ 
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						emit("timeOut", "timeOut(0)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
