/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val slotmap = domain.Hold("properties.txt")
		
		        val StepTime = 345
		        var PlanDone = "''"
		    	var PlanToDo = "''"
		    	var Arg = "''"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | starts, in attesa di richieste da cargoservice")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [READY] in attesa")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="handleMoveToSlot",cond=whenRequest("movetoslot"))
					transition(edgeName="t020",targetState="handleStartOOS",cond=whenDispatch("startOOS"))
					transition(edgeName="t021",targetState="handleEndOOS",cond=whenDispatch("endOOS"))
					transition(edgeName="t022",targetState="discardStaleReply",cond=whenReply("moverobotdone"))
					transition(edgeName="t023",targetState="discardStaleReply",cond=whenReply("moverobotfailed"))
				}	 
				state("discardStaleReply") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | SCARTATO messaggio obsoleto da robotsmart")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handleMoveToSlot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("movetoslot(SLOTN)"), Term.createTerm("movetoslot(SLOTN)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            	val SlotTarget = payloadArg(0)
								                val target = slotmap.coordinatesOf(SlotTarget)
								                val TX = target.getX()
								                val TY = target.getY()
								CommUtils.outcyan("$name | ricevuto movetoslot($SlotTarget) -> target ($TX,$TY)")
								request("moverobot", "moverobot($TX,$TY,$StepTime)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t124",targetState="replySuccessToCaller",cond=whenReply("moverobotdone"))
					transition(edgeName="t125",targetState="replyFailureToCaller",cond=whenReply("moverobotfailed"))
					transition(edgeName="t126",targetState="handleStartOOS",cond=whenDispatch("startOOS"))
				}	 
				state("replySuccessToCaller") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotok(ARG)"), Term.createTerm("moverobotok(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								Arg= payloadArg(0) 
						}
						answer("movetoslot", "movetoslotdone", "movetoslotdone($Arg)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("replyFailureToCaller") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        		val PlanDone= payloadArg(0)
								        		val PlanToDo= payloadArg(1)
								CommUtils.outred("$name | movimento fallito, plan done=$PlanDone todo=$PlanToDo")
						}
						answer("movetoslot", "movetoslotfailed", "movetoslotfailed($PlanDone,$PlanToDo)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handleStartOOS") { //this:State
					action { //it:State
						CommUtils.outred("$name | [OOS] segnalo alarm a robotsmart26")
						emit("alarm", "alarm(1)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t327",targetState="handleEndOOS",cond=whenDispatch("endOOS"))
				}	 
				state("handleEndOOS") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [OOS] fine allarme, torno operativo")
						emit("loadEnded", "loadEnded(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
