/* Generated by AN DISI Unibo */ 
package it.unibo.sensor

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sensor ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		    	val DFREE = 80
			    var belowSince = 0L
			    var aboveSince = 0L
			    var restoreSince = 0L
			    var faulted = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://mosquitto:1883" )
						subscribe(  "picosonar/data" ) //mqtt.subscribe(this,topic)
						CommUtils.outcyan("$name | starts - Sensore")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="monitoring", cond=doswitch() )
				}	 
				state("monitoring") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t030",targetState="handleReading",cond=whenEvent("sonardata"))
				}	 
				state("handleReading") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonardata(D)"), Term.createTerm("sonardata(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val dist = payloadArg(0).toInt()
								                val now = System.currentTimeMillis()
								if(  dist < DFREE/2  
								 ){ if (belowSince == 0L) belowSince = now; aboveSince = 0L; restoreSince = 0L 
								if(  belowSince != 0L && (now - belowSince) >= 3000  
								 ){CommUtils.outgreen("$name | Rilevato container in sensor area")
								emit("containerDetected", "containerDetected(1)" ) 
								 belowSince = 0L  
								}
								}
								else
								 {if(  dist > DFREE  
								  ){ if (aboveSince == 0L) aboveSince = now; belowSince = 0L; restoreSince = 0L 
								 if(  aboveSince != 0L && (now - aboveSince) >= 3000 && faulted == false  
								  ){CommUtils.outred("$name | Rilevato sistema compromesso, emetto allarme")
								 emit("sensorAlarm", "sensorAlarm(1)" ) 
								  faulted = true  
								 }
								 }
								 else
								  {
								  				        if (restoreSince == 0L) restoreSince = now
								  				        belowSince = 0L
								  				        aboveSince = 0L
								  if(  restoreSince != 0L && (now - restoreSince) >= 3000 && faulted == true  
								   ){CommUtils.outcyan("$name | Guasto risolto")
								  emit("sensorRestored", "sensorRestored(1)" ) 
								   faulted = false; restoreSince = 0L  
								  }
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="monitoring", cond=doswitch() )
				}	 
			}
		}
} 
