/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://mosquitto:1883" )
						CommUtils.outgreen("$name | starts - bridge verso PicoW-led su eventTopic")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t028",targetState="handleStart",cond=whenDispatch("startBlink"))
					transition(edgeName="t029",targetState="handleStop",cond=whenDispatch("stopBlink"))
				}	 
				state("handleStart") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("startBlink(X)"), Term.createTerm("startBlink(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								               val Freq = payloadArg(0)
								               val msg = MsgUtil.buildDispatch(name, "startBlink", "startBlink($Freq)", "picosonar")
								               mqtt.publish("picosonar/led", msg.toString())
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handleStop") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stopBlink(X)"), Term.createTerm("stopBlink(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								               val Freq = payloadArg(0)
								               val msg = MsgUtil.buildDispatch(name, "stopBlink", "stopBlink($Freq)", "picosonar")
								               mqtt.publish("picosonar/led", msg.toString())
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
