/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
		        lateinit var gui: guiout.IoPortGuiHandler 
		        lateinit var coapObserver: guiout.CargoServiceCoapObserver
		        var Num = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
						            gui = guiout.IoPortGuiHandler("guih", 8050, myself)
						            coapObserver = guiout.CargoServiceCoapObserver("127.0.0.1", 8120, "ctxcargosystem", "cargoservice", gui)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ready", cond=doswitch() )
				}	 
				state("ready") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [READY] In attesa di input...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleButtonPressed",cond=whenDispatch("buttonPressed"))
				}	 
				state("handleButtonPressed") { //this:State
					action { //it:State
						 Num++  
						CommUtils.outgreen("$name | Bottone premuto! Richiesta inviata")
						request("loadRequest", "loadRequest($Num)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitch() )
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | [ENGAGED] Richieste disabilitate.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="ready",cond=whenEvent("loadEnded"))
					transition(edgeName="t12",targetState="ready",cond=whenEvent("timeOut"))
					transition(edgeName="t13",targetState="ready",cond=whenReply("loadRejected"))
					transition(edgeName="t14",targetState="ready",cond=whenReply("retryLater"))
				}	 
			}
		}
} 
