/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 lateinit var gui: guiout.IoPortGuiHandler  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
							        // Istanza server javalin
							        val gui = guiout.IoPortGuiHandler("guih", 8050, myself)
						CommUtils.outmagenta("$name | starts - Avvio Server WebGUI su porta 8050")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="running", cond=doswitch() )
				}	 
				state("running") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | In attesa di input dall'utente...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleButtonPressed",cond=whenDispatch("buttonPressed"))
				}	 
				state("handleButtonPressed") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Bottone premuto! Richiesta inoltrata a CargoService")
						request("loadRequest", "loadRequest(1)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="handleEngaged",cond=whenReply("loadEngaged"))
					transition(edgeName="t12",targetState="handleReject",cond=whenReply("loadRejected"))
					transition(edgeName="t13",targetState="handleRetry",cond=whenReply("retryLater"))
				}	 
				state("handleEngaged") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadEngaged(SLOT)"), Term.createTerm("loadEngaged(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val slotName = payloadArg(0)  
								CommUtils.outgreen("$name | Carico Accettato: $slotName")
								 gui.updateState("engaged", "Service working: Carico in $slotName")  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="running", cond=doswitch() )
				}	 
				state("handleReject") { //this:State
					action { //it:State
						CommUtils.outred("$name | Carico Rifiutato (Hold Piena)")
						 gui.updateState("disengaged", "Richiesta rifiutata: Hold piena")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="running", cond=doswitch() )
				}	 
				state("handleRetry") { //this:State
					action { //it:State
						CommUtils.outred("$name | Sistema occupato, riprovare")
						 gui.updateState("engaged", "Sistema occupato. Riprovare più tardi.")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="running", cond=doswitch() )
				}	 
			}
		}
} 
