/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val hold = domain.HoldManager("properties.txt")
		
		        var engaged = false			
		        var SlotTarget : domain.ISlot? = null  
		        var IoPort = "ioport"
		        var Slot5 = "slot5"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | starts - Inizializzazione Orchestratore Cargo Service")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 engaged = false 
						       val holdState = hold.toString().replace("\n", "\\n").replace("\"", "\\\"")
						       val JsonMsg = "{\"state\":\"disengaged\", \"message\":\"Service working - In attesa di richieste\", \"hold\":\"$holdState\"}" 
						CommUtils.outgreen("$name | [DISENGAGED] attendo request")
						updateResourceRep( JsonMsg  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("loadRequest"))
					interrupthandle(edgeName="t01",targetState="handleAlarm",cond=whenEvent("sensorAlarm"),interruptedStateTransitions)
					transition(edgeName="t02",targetState="discardStaleReplyCargoService",cond=whenReply("movetoslotdone"))
					transition(edgeName="t03",targetState="discardStaleReplyCargoService",cond=whenReply("movetoslotfailed"))
				}	 
				state("discardStaleReplyCargoService") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | [DISENGAGED] Scartato messaggio obsoleto da cargorobot")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  !hold.isFull() && engaged == false  
						 ){ 
							    		val freeSlot = hold.findFreeSlot()
							    		SlotTarget = freeSlot	
							    		val SlotTargetId = freeSlot?.getName() ?: "Unknown"
							    		engaged = true
						                val holdState = hold.toString().replace("\n", "\\n")
							    		val JsonMsg = "{\"state\":\"engaged\", \"message\":\"Service working - Slot assegnato: $SlotTargetId\", \"hold\":\"$holdState\"}" 
						answer("loadRequest", "loadEngaged", "loadEngaged($SlotTargetId)"   )  
						updateResourceRep( JsonMsg  
						)
						forward("startBlink", "startBlink(0)" ,"led" ) 
						CommUtils.outmagenta("$name | [ENGAGED] Request di carico accettata, slot disponibile: $SlotTargetId")
						}
						else
						 {if(  engaged == true  
						  ){answer("loadRequest", "retryLater", "retryLater(0)"   )  
						 }
						 else
						  {answer("loadRequest", "loadRejected", "loadRejected(0)"   )  
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingContainer", cond=doswitchGuarded({ engaged == true  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( engaged == true  
					) }) )
				}	 
				state("waitingContainer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [ENGAGED] attendo container entro 30s")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitingContainer", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitingContainer", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t14",targetState="handleTimeoutExpired",cond=whenTimeout("local_tout_"+name+"_waitingContainer"))   
					transition(edgeName="t15",targetState="handleContainerDetected",cond=whenEvent("containerDetected"))
					transition(edgeName="t16",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("handleTimeoutExpired") { //this:State
					action { //it:State
						CommUtils.outred("$name | [DISENGAGED] Timeout 30s scaduto, back to disengaged")
						
						            engaged = false
						            val holdState = hold.toString().replace("\n", "\\n")
						       		val JsonMsg = "{\"state\":\"disengaged\", \"message\":\"Richiesta fallita: tempo scaduto (30s)\", \"hold\":\"$holdState\"}" 
						updateResourceRep( JsonMsg  
						)
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						emit("timeOut", "timeOut(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleContainerDetected") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outgreen("$name | [ENGAGED] Container rilevato ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startMoveToSensorArea", cond=doswitch() )
				}	 
				state("startMoveToSensorArea") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [ENGAGED] Robot move container verso Sensor Area")
						request("movetoslot", "movetoslot($IoPort)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="startMoveToSlot5",cond=whenReply("movetoslotdone"))
					transition(edgeName="t08",targetState="handleDepositFailed",cond=whenReply("movetoslotfailed"))
					transition(edgeName="t09",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("startMoveToSlot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | [ENGAGED] Carico recuperato in sensor area! Robot muove container verso Slot5")
						request("movetoslot", "movetoslot($Slot5)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="markingSlot5",cond=whenReply("movetoslotdone"))
					transition(edgeName="t011",targetState="handleDepositFailed",cond=whenReply("movetoslotfailed"))
					transition(edgeName="t012",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("markingSlot5") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [ENGAGED] container arrivato in slot5: inizio procedura di labeling ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_markingSlot5", 
				 	 					  scope, context!!, "local_tout_"+name+"_markingSlot5", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t013",targetState="startMoveToSlot",cond=whenTimeout("local_tout_"+name+"_markingSlot5"))   
					transition(edgeName="t014",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("startMoveToSlot") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [ENGAGED] container etichettato, robot in movimento verso $SlotTarget")
						 val SlotTargetId = SlotTarget?.getName() ?: "Unknown"  
						request("movetoslot", "movetoslot($SlotTargetId)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="handleDepositSuccess",cond=whenReply("movetoslotdone"))
					transition(edgeName="t016",targetState="handleDepositFailed",cond=whenReply("movetoslotfailed"))
					transition(edgeName="t017",targetState="handleAlarm",cond=whenEvent("sensorAlarm"))
				}	 
				state("handleDepositSuccess") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [DISENGAGED] container depositato con successo nello slot $SlotTarget")
						
									SlotTarget?.putContainer()
									val holdState = hold.toString().replace("\n", "\\n")
									engaged = false
									val slotName = SlotTarget?.getName() ?: "Unknown"
									val JsonMsg = "{\"state\":\"disengaged\", \"message\":\"Carico completato: slot $slotName\", \"hold\":\"$holdState\"}"
						updateResourceRep( JsonMsg  
						)
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						emit("loadEnded", "loadEnded(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleDepositFailed") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outred("$name | [DISENGAGED] deposito fallito")
						 
									engaged = false 
						            val holdState = hold.toString().replace("\n", "\\n")
									val JsonMsg = "{\"state\":\"disengaged\", \"message\":\"Errore: deposito fallito\", \"hold\":\"$holdState\"}"
						updateResourceRep( JsonMsg  
						)
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						forward("endOOS", "endOOS(0)" ,"cargorobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outred("$name | [OUT OF SERVICE] Allarme Out of Service rilevato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfService", cond=doswitch() )
				}	 
				state("outOfService") { //this:State
					action { //it:State
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						forward("startOOS", "startOOS(0)" ,"cargorobot" ) 
						CommUtils.outred("$name | [OUT OF SERVICE] Sistema in allarme")
						 
						            val holdState = hold.toString().replace("\n", "\\n")
						            val JsonMsg = "{\"state\":\"outofservice\", \"message\":\"Out of service\", \"hold\":\"$holdState\"}"
						updateResourceRep( JsonMsg  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="handleEndOOS",cond=whenEvent("sensorRestored"))
				}	 
				state("handleEndOOS") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | [OOS] Fine allarme, ripristino stato iniziale")
						 
								    engaged = false
								    SlotTarget = null
								    val holdState = hold.toString().replace("\n", "\\n")
								    val JsonMsg = "{\"state\":\"disengaged\", \"message\":\"Ripristinato da OOS - Sistema inattivo\", \"hold\":\"$holdState\"}"
						updateResourceRep( JsonMsg  
						)
						forward("stopBlink", "stopBlink(0)" ,"led" ) 
						forward("endOOS", "endOOS(0)" ,"cargorobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
