version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    networks:
      - iss-network

  cargosystem:
    container_name: cargosystem
    hostname: cargosystem
    image: cargosystem:1.0
    build:
      context: ./CargoSystem26
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8120:8120/tcp"
      - "8120:8120/udp"
    environment:
      - MQTTBROKER=mosquitto
    depends_on:
      - mosquitto
    networks:
      - iss-network

  webgui:
    container_name: webgui
    hostname: webgui
    image: webgui:1.0
    build:
      context: ./WebGUI
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8050:8050/tcp"   # Porta per accedere al sito dal browser
      - "8040:8040/tcp"   # Porta di comunicazione QAk (TCP)
      - "8040:8040/udp"   # Porta di comunicazione QAk (UDP)
    environment:
      - MQTTBROKER=mosquitto
    depends_on:
      - cargosystem
      - mosquitto
    networks:
      - iss-network

  wenv:
    container_name: wenv
    image: docker.io/natbodocker/virtualrobotdisi26:1.0
    ports:
      - "8090:8090"
      - "8091:8091/tcp"
      - "8091:8091/udp"
    networks:
      - iss-network

  robotoutgui25:
    container_name: robotoutgui25
    image: docker.io/natbodocker/robotoutgui25:1.0
    ports:
      - "8085:8085/tcp"
    networks:
      - iss-network

  robotsmart26:
    container_name: robotsmart26
    image: docker.io/natbodocker/robotsmart26:1.0
    mem_limit: 512m
    ports:
      - "8020:8020/tcp"
      - "8020:8020/udp"
    environment:
      - VIRTUAL_ENV=wenv       # Used by VRObj26 connect
      - MQTTBROKER=mosquitto
    depends_on:
      - wenv
    networks:
      - iss-network

networks:
  iss-network:
    external: true
